### ISSUE TITLE
Some licenses not reported

### ISSUE THREAD

**Issue by kivra-pauoli** [voltone/rebar3_sbom#16]
👋 

First of all, great work on this plugin.

I'm using it in CI to automate license validation.

I'm wondering, though, why certain licenses aren't present, like e.g. `ssl_verify_fun`'s MIT, `ranch`'s ISC, etc.

I'm mostly pulling from Hex, and am willing to go **knock on doors** where information is missing, but (I didn't yet look at the code) it's possible starting here is a good option.

Also willing (and able) to pull request to "fix"/"improve" whatever the plugin needs, regarding the issue at hand.

Thanks.

**Comment by voltone** [comment]
Currently the plugin works on data provided by Rebar3, it just converts that data to CycloneDX format. If Rebar3 doesn't know the license, because the project's [rebar.config](https://github.com/deadtrickster/ssl_verify_fun.erl/blob/master/rebar.config) does not specify it or the [project uses Erlang.mk](https://github.com/ninenines/ranch) as the build system, then no license information is returned by the Rebar3 plugin API.

For dependencies that use Rebar3 you could propose a PR to add a license identifier to the config file. For non-Rebar3 projects it may be possible to add a fallback to the plugin that checks the Hex package contents for a LICENSE file, and then apply some heuristics to guess what license it is. But that's a lot more work.

**Comment by kivra-pauoli** [comment]
👋

> because the project's [rebar.config](https://github.com/deadtrickster/ssl_verify_fun.erl/blob/master/rebar.config) does not specify it

Do you mean the `.app.src`, instead (this is the case with e.g. `unicode_util_compat`: [`.app.src`](https://github.com/benoitc/unicode_util_compat/blob/master/src/unicode_util_compat.app.src) v. [`rebar.config`](https://github.com/benoitc/unicode_util_compat/blob/master/rebar.config))? I don't remember putting license info in `rebar.config`. 🤔 

`ssl_verify_fun`'s [`.app.src`](https://github.com/deadtrickster/ssl_verify_fun.erl/blob/master/src/ssl_verify_fun.app.src) doesn't have `licenses` for example, which would explain why it's not showing up.

I'll make sure to start asking the maintainers to populate that (and/or pull requesting) with this topic as a reference.

Thanks much, @voltone.

**Comment by kivra-pauoli** [comment]
For future reference, this is also worth noting: https://github.com/voltone/rebar3_sbom/blob/master/src/rebar3_sbom_cyclonedx.erl#L49.

If the license is not "SPDX"-based it'll get reported in field `name`, not `id` (which already reduces our list of no-license outputs) 😄

**Comment by kivra-pauoli** [comment]
@voltone, thank you for the discussion. I've started other discussions and/or pull requests, where appropriate. This is not a `rebar3_sbom` -specific issue, so I'm gonna close this one. 👍
